routes/admin.php
<?php

use App\Http\Controllers\admin\AdController;
use App\Http\Controllers\admin\BannerController;
use App\Http\Controllers\admin\CategoriesController;
use App\Http\Controllers\admin\DatabaseProductController;
use App\Http\Controllers\admin\EducationalDetails;
use App\Http\Controllers\admin\FormsController;
use App\Http\Controllers\admin\HighlighController;
use App\Http\Controllers\admin\JobsController;
use App\Http\Controllers\admin\LocationController;
use App\Http\Controllers\admin\PackagesController;
use App\Http\Controllers\admin\PagesController;
use App\Http\Controllers\admin\ProductsController;
use App\Http\Controllers\admin\SettingsController;
use App\Http\Controllers\admin\TestimonialController;
use App\Http\Controllers\admin\UserBackgroundVerificationController;
use App\Http\Controllers\admin\UsersController;
use App\Http\Controllers\admin\VerificationPackageController;
use App\Http\Controllers\AdminDashboard;
use App\Http\Controllers\admin\AdminsController;
use App\Http\Controllers\admin\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\FunctionalAreaController;
use App\Http\Controllers\IndustryTypeController;
use App\Http\Controllers\LgaController;
use App\Http\Controllers\SkillsController;
use App\Http\Controllers\StateController;
use App\Models\DatabaseProduct;
use App\Models\UserBackgroundVerification;


Route::group(['middleware' => ['auth','role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('dashboard', AdminDashboard::class)->name('dashboard');

//    User Listing

    Route::get('user/admins', [UsersController::class, 'admins'])->name('user.admins');
    Route::get('user/sub_admins', [UsersController::class, 'subAdmins'])->name('user.sub_admins');
    Route::get('user/employers', [UsersController::class, 'employers'])->name('user.employers');
    Route::get('user/jobseekers', [UsersController::class, 'jobseekers'])->name('user.jobseekers');
    Route::post('settings/store/item', [SettingsController::class, 'storeItem'])->name('settings.store.item');

    Route::get('pages/edit/page', [PagesController::class, 'editPage'])->name('pages.edit.page');

    Route::get('resume/access', [AdminsController::class, 'resumeAccess'])->name('resume.access');
    Route::get('inactive/resumes', [AdminsController::class, 'inactiveResumes'])->name('inactive.resumes');
    Route::post('resume/search', [AdminsController::class, 'resumeSearch'])->name('resume.search');
    Route::get('inactive/companies', [AdminsController::class, 'inactiveCompanies'])->name('inactive.companies');

    Route::get('employee/database/access', [AdminsController::class, 'employeeDBAccess'])->name('employee.db.access');
    Route::get('employee/database/order', [AdminsController::class, 'employeeDBAccessOrders'])->name('employee.db.access.orders');
    Route::get('employee/job/access/order', [AdminsController::class, 'employeeJobAccessOrders'])->name('employee.job.access.orders');
    Route::get('employee/job/access', [AdminsController::class, 'employeeJobAccess'])->name('employee.job.access');

    Route::get('package/purchased', [AdminsController::class, 'packagePurchased'])->name('package.purchased');

    Route::get('background/forms', [FormsController::class, 'backgroundIndex'])->name('background.form.index');

    Route::get('background/submissions', [UserBackgroundVerificationController::class, 'index'])->name('background.submissions');

    Route::get('background/submission/{id}', [UserBackgroundVerificationController::class, 'show'])->name('background.submission');
    Route::get('background/upload/{id}', [UserBackgroundVerificationController::class, 'upload'])->name('background.upload');
    Route::post('background/upload/store', [UserBackgroundVerificationController::class, 'storeUpload'])->name('background.upload.store');
    Route::get('background/approve/{id}', [UserBackgroundVerificationController::class, 'approve'])->name('background.approve');

    Route::get('settings/home', [SettingsController::class, 'home'])->name('settings.home');

    Route::get('jobseeker/newsletter', [AdminsController::class, 'jobseekerNewsletter'])->name('jobseeker.newsletter');
    Route::get('employer/newsletter', [AdminsController::class, 'employerNewsletter'])->name('employer.newsletter');
    Route::post('newsletter/submit', [AdminsController::class, 'newsletterSubmit'])->name('newsletter.submit');

    Route::post('newsletter/send', [AdminsController::class, 'newsletterSend'])->name('newsletter.send');

    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    

    Route::resources([
        'countries' => CountryController::class,
        'highlights' => HighlighController::class,
        'users' => UsersController::class,
        'lgas' => LgaController::class,
        'states' => StateController::class,
        'cities' => CityController::class,
        'skills' => SkillsController::class,
        'industry-type'     => IndustryTypeController::class,
        'functional-area'   => FunctionalAreaController::class,
        'educational-details' => EducationalDetails::class,
        'products' => ProductsController::class,
        'ads' => AdController::class,
        'packages' => PackagesController::class,
        'pages' => PagesController::class,
        'banners' => BannerController::class,
        'settings' => SettingsController::class,
        'categories' => CategoriesController::class,
        'locations' => LocationController::class,
        'testimonial' => TestimonialController::class,
        'dbproducts' => DatabaseProductController::class,
        'v_packages' => VerificationPackageController::class,
        'forms' => FormsController::class,
        '/home/jobs' => JobsController::class,

    ]);

});

routes/web.php
<?php


use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobAlertController;
use App\Http\Controllers\JobsController;
use App\Http\Controllers\JobseekerController;
use App\Http\Controllers\admin\TempController;
use App\Http\Controllers\LocationsController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SocialAuthController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;



Route::get('login/{provider}', [SocialAuthController::class,'redirect'])->name('social.login');
Route::get('login/{provider}/callback', [SocialAuthController::class,'callback']);

Route::get('/',[HomeController::class, 'index'])->name('home');

Route::get('/similar/jobs',[JobsController::class, 'similar'])->name('similar');

Route::post('/contact/storeemp_resume_pack',[HomeController::class, 'storeContact'])->name('contact.store');


Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/testimonial',[HomeController::class, 'testimonial'])->name('testimonial');

Route::post('/testimonial/store',[HomeController::class, 'testimonialStore'])->name('testimonial.store');

Route::get('payment-razorpay',  [PaymentController::class,'create'])->name('paywithrazorpay');
Route::post('payment', [PaymentController::class,'payment'])->name('payment');
Route::post('verification/payment', [PaymentController::class,'verificationPayment'])->name('verification.payment');

Route::get('/about-us',[HomeController::class, 'about'])->name('about');
Route::get('/terms',[HomeController::class, 'terms'])->name('terms');
Route::get('/privacy',[HomeController::class, 'privacy'])->name('privacy');
Route::get('/faq',[HomeController::class, 'faq'])->name('faq');

Route::get('/getstates', [LocationsController::class, 'getstates'])->name('ajax.getstates');


Route::post('/payment/store', 'PaymentController@store')->name('payment.store');



Route::get('jobseeker-self-service', [HomeController::class, 'jobseekerSelfservice'])->name('selfservice');
Route::get('background-verification-request', [HomeController::class, 'backgroundVerificationRequest'])->name('bg_verification');
Route::get('background-verification-response', [HomeController::class, 'backgroundVerificationResponse'])->name('bg_verification_response');
Route::get('background-verification-payment/{id}', [HomeController::class, 'backgroundVerificationPayment'])->name('bg_verification_pay');
Route::get('background-verification', [HomeController::class,'backgroundVerification'])->name('background-verification');
Route::get('background-verification/2/{id}', [HomeController::class,'backgroundVerification2'])->name('background-verification-2');
Route::get('background-verification/3/{id}', [HomeController::class,'backgroundVerification3'])->name('background-verification-3');

Route::post('background-edu-store', [HomeController::class,'storeEdu'])->name('store.edu');
Route::post('background-employment-store', [HomeController::class,'storeEmployment'])->name('store.employment');
Route::post('background-ref-store', [HomeController::class,'storeRef'])->name('store.ref');

//Route::view('background-verification/2', 'background-verification2')->name('background-verification-2');
//Route::view('background-verification/3', 'background-verification3')->name('background-verification-3');


Route::post('/advance_search',[JobsController::class, 'advanceSearch'])->name('advance_search');

Route::get('/company/{id}/jobs',[JobsController::class, 'companyAllJobs'])->name('company.all.jobs');

Route::resources([
    'users' => UsersController::class,
]);

Route::post('/update/password',[UsersController::class, 'updatePassword'])->name('update.password');

Route::post('/mail/job',[HomeController::class, 'mailJob'])->name('mail.job');
Route::post('/mail/employer',[HomeController::class, 'mailEmployer'])->name('mail.employer');


Route::get('/jobseeker-registeration', [UsersController::class,'jobseekerReg'])->name('jobseeker.reg');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/jobseeker/register', [UsersController::class, 'jobseekerReg'])->name('jobseeker.register');
    Route::get('/jobseeker/login', [UsersController::class, 'jobseekerLogin'])->name('jobseeker.login');

    Route::get('/employer/register', [UsersController::class,'employerReg'])->name('employer.register');
    Route::get('/employer/login', [UsersController::class,'employerLogin'])->name('employer.login');

});

Route::Resources(['job_alerts' => JobAlertController::class]);


Route::group(['prefix' => 'jobseeker','middleware' => ['verified','auth','role:jobseeker|admin']], function () {

    Route::get('/profile', [JobseekerController::class, 'profile'])->name('jobseeker.profile');
    Route::get('/manage/employers', [JobseekerController::class, 'employers'])->name('jobseeker.manage.employers');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/edit-employee/{id}', [JobseekerController::class,'editEmployee'])->name('edit_emp');
    Route::post('/delete-employee/{id}', [JobseekerController::class,'deleteEmployer'])->name('delete_emp');

    Route::post('/job/apply', [JobsController::class,'apply'])->name('job.apply');



});


Route::group(['middleware' => ['verified','auth']], function () {

    Route::post('/user/update/resume', [UsersController::class, 'updateResume'])->name('user.update.resume');
    Route::post('/user/create/employer', [UsersController::class, 'storeEmployer'])->name('user.create.employer');

    Route::post('/user/update/account', [UsersController::class, 'update'])->name('user.account.update');
    Route::post('/user/update/summary', [UsersController::class, 'updateSummary'])->name('user.account.summary');
    Route::post('/user/update/more', [UsersController::class, 'updateMore'])->name('user.update.more');
    Route::post('/user/update/education', [UsersController::class, 'updateEducation'])->name('user.update.education');

    Route::get('/user/profile/{username}', [UsersController::class, 'userProfile'])->name('user.profile.public');
    Route::get('/user/download/resume/{username}', [UsersController::class, 'downloadResume'])->name('user.resume.download');

    Route::post('/user/update/itskills', [UsersController::class, 'updateItskills'])->name('user.update.itskills');

    Route::post('/user/update/avatar', [UsersController::class, 'updateAvatar'])->name('user.update.avatar');
    Route::post('/user/update/visibility', [UsersController::class, 'updateVisibility'])->name('user.update.visibility');

    Route::get('/edit-summary-info', [UsersController::class,'editSummary'])->name('edit_summary');
    Route::get('/create-employee', [JobseekerController::class,'createEmployee'])->name('create_emp');
    Route::get('/edit-resume-detail', [JobseekerController::class,'editResume'])->name('edit_resume_det');
    Route::get('/itskills', [JobseekerController::class,'itSkills'])->name('itskills');
    Route::get('/educationdetails', [JobseekerController::class,'eduDetails'])->name('educational_details');
    Route::get('/moredetails', [JobseekerController::class,'moredetails'])->name('moredetails');
    Route::get('/jobseeker-profile-edit', [JobseekerController::class,'profileEdit'])->name('jobseeker-edit');

});

Route::group(['prefix' => 'employer','middleware' => ['verified','auth','role:employer|admin']], function () {


    Route::post('/purchase/plan',[HomeController::class, 'purchasePlan'])->name('plan.purchase');


    Route::get('/profile', [EmployerController::class, 'profile'])->name('employer.profile');
    Route::get('/emp_resume_pack', [EmployerController::class, 'empResumePack'])->name('employer.resume_pack');
    Route::get('/transactions', [EmployerController::class, 'Transactions'])->name('employer.transactions');
    Route::get('/transaction/payment/{type}/{id}', [EmployerController::class, 'TransactionPayment'])->name('employer.transaction.payment');
    Route::get('/sub_users', [EmployerController::class, 'subUsers'])->name('employer.sub_users');
    Route::get('/add_sub_user', [EmployerController::class, 'addSubUser'])->name('employer.add_sub_user');

    Route::get('/featured_resume', [EmployerController::class, 'featuredResume'])->name('employer.featured_resumes');
    Route::post('/search_resume', [EmployerController::class, 'searchResume'])->name('search_resumes');

    Route::get('/change/password', [EmployerController::class, 'changePassword'])->name('employer.change_password');
    Route::get('/job/{slug}', [JobsController::class, 'view'])->name('jobs.job.view');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/job/{id}/responses', [JobsController::class, 'response'])->name('job.response');


    Route::get('/jobs/deleted', [JobsController::class, 'deleted'])->name('jobs.deleted');
    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    Route::get('/jobs/restore/deleted/job/{slug}/{id}', [JobsController::class, 'restore'])->name('jobs.restore');
    Route::post('/jobs/force/delete/{id}', [JobsController::class, 'forceDelete'])->name('jobs.delete');

    Route::post('/user/update', [UsersController::class, 'updateProfile'])->name('user.update');
    Route::post('/user/store/sub', [UsersController::class, 'storeSubUser'])->name('user.sub.store');

    Route::resources([
        'jobs' => JobsController::class,
        'companies' => CompaniesController::class,
        'jobs' => jobsController::class,
        ]);
});




Route::get('/all-jobs', [JobsController::class, 'allJobs'])->name('all_jobs');

Route::get('/job/{slug}', [JobsController::class, 'jobView'])->name('jobs.job.view');


Route::get('/jobs-by-area', [JobsController::class,'jobByArea'])->name('job_by_area');

resources/views/background-verification.blade.php
@extends('layouts.verification')

@section('head')
    <div class="row">
        <div class="col-md-12">
            <div class="banner-headline">
                <h3>
                    <strong style="color: white">Background Verification 1.</strong>

                </h3>
            </div>
        </div>
    </div>
@endsection

@section('content')


    <!-- Category Boxes -->
    <div class="section margin-top-65">
        <div class="container">

            <div class="row">

                <!-- Dashboard Box -->
                <div class="col-lg-10 offset-md-1">
                    <div class="dashboard-box margin-top-0">

                        <!-- Headline -->
                        <div class="headline">
                            <h4>Hire Ready Application Form ({{ $package->name }})</h4>
                            <p> Employment Details - Step 1 of 3</p>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"></div>
                            </div>
                        </div>

                        <div class="content with-padding padding-bottom-10">
                            <form method="POST" action="{{ route('store.employment') }}">
                                @csrf

                                <div class="row">
                                @foreach (\App\Models\Form::whereModel('verification_user_forms')->wherePage(1)->get() as $item)
                                    @if ($item->type == 'country')
                                        <div class="col-md-{{ $item->rows }}">
                                            <div class="submit-field">
                                                <h5 class="text-capitalize">{{ str_replace('_',' ',$item->name) }}
                                                    @if ($item->required)
                                                        <span class="text text-danger">*</span>
                                                    @endif
                                                </h5>
                                                <select name="employments[country]" class="form-control country_select select2" data-size="7" title="Select country Type">
                                                    <option>Select Country</option>
                                                    @foreach(\App\Models\Country::pluck('name') as $item)
                                                        <option  value="{{ $item }}">{{ $item }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    @elseif ($item->type == 'state')
                                        <div class="col-md-{{ $item->rows }}">
                                            <div class="submit-field">
                                                <h5 class="text-capitalize">{{ str_replace('_',' ',$item->name) }}
                                                    @if ($item->required)
                                                        <span class="text text-danger">*</span>
                                                    @endif
                                                </h5>
                                                <select style="width: 100%" class="form-control select2 states" required name="employments[state]">

                                                    <option>Select Country first</option>

                                                </select>
                                            </div>
                                        </div>
                                    @elseif ($item->type == 'textarea')
                                        <div class="col-md-{{ $item->rows }}">
                                            <div class="submit-field">
                                                <h5 class="text-capitalize">{{ str_replace('_',' ',$item->name) }}
                                                    @if ($item->required)
                                                        <span class="text text-danger">*</span>
                                                    @endif
                                                </h5>
                                                <textarea rows="3" class="" required="{{ $item->required }}"  name="employments[{{$item->name}}]"></textarea>
                                            </div>
                                        </div>
                                    @else
                                        <div class="col-md-{{ $item->rows }}">
                                            <div class="submit-field">
                                                <h5 class="text-capitalize">{{ str_replace('_',' ',$item->name) }}
                                                    @if ($item->required)
                                                        <span class="text text-danger">*</span>
                                                    @endif
                                                </h5>
                                                <input class="with-border" required="{{ $item->required }}" name="employments[{{$item->name}}]" placeholder="{{ str_replace('_',' ',$item->name) }}">
                                            </div>
                                        </div><!-- col-8 -->
                                    @endif
                                @endforeach
                                    <input type="hidden" name="package" value="{{ $package->id }}">

                                </div>
                                <div class="col-xl-12">
                                    {{--                        href="{{ route('background-verification-2') }}?package={{$package->id}}"--}}
                                    <button type="submit"  class="button ripple-effect big margin-top-30"><i class="icon-feather-plus"></i> Next</button>
                                </div>
                            </form>
                        </div>

                    </div>

                </div>


            </div>

        </div>
    </div>


@endsection

@section('style')
    <link rel="stylesheet" href="{{ asset('/css/select2.css') }}">
@endsection

@section('js')

    <script src="{{ asset('/js/select2.full.js')}}" type="text/javascript"></script>


    <script type="text/javascript">
        $(document).ready(function() {
            $('.select2').select2({});
            $(".country_select").on('select2:select', function (e) {
                let country = e.params.data.id;
                $.ajax({
                    url: '{{route('ajax.getstates')}}?country=' + country,
                    method: 'GET',
                    error: function () {
                    },
                    success: function (response) {
                        $(".states").empty();
                        $.each(response.states, function (index, value) {
                            $(".states").append(`<option value=${value.name}>${value.name}</option>`);
                        });
                    },
                    complete: function () {

                    }
                });
            });
        });
    </script>


@endsection

resources/views/bg_verification_response.blade.php
@extends('layouts.master')

@section('content')
    <!-- CONTENT -->
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-md-0"></div>
                <div class="col-md-11">
                    <ol class="breadcrumb">
                        <li><a href="{{ url('/') }}">Home</a></li>
                        <li class="active">Background Verification Response</li>
                    </ol>
                </div>

                @include('employer.partials.sidebar')


                <div class="col-md-9" >

                    <div class="br-pagebody">
                        <div class="br-section-wrapper">
                            <h4 style="padding-bottom: 10px; padding-top: 10px" class="tx-gray-800 text-center tx-uppercase tx-bold"> Background Verification Submissions</h4>

                            <div class="table-wrapper">
                                <table id="datatable1" class="table display table-condensed table-bordered responsive nowrap">
                                    <thead>
                                    <tr>
                                        <th class="wd-5p"> S.No</th>
                                        <th class="wd-30p">User Name</th>
                                        <th class="wd-20p">Package</th>
                                        <th class="wd-10p">Payment</th>
                                        <th class="wd-10p">Status</th>
                                        <th class="wd-15p"> Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($bgs as $user)
                                        <tr>
                                            <td>{{ $user->id }}</td>
                                            <td>{{ optional($user->user)->name }}</td>
                                            <td>{{ optional($user->package)->name }}</td>
                                            <td>{{ $user->paid ? 'Paid' : 'Unpaid' }}</td>
                                            <td>{{ $user->status }}</td>

                                            <td class="text-center">
                                                {{--                                <form method="POST" action="{!! route('admin.locations.destroy', $user->id) !!}" accept-charset="UTF-8">--}}
                                                {{--                                    <input name="_method" value="DELETE" type="hidden">--}}
                                                {{--                                    {{ csrf_field() }}--}}


                                                @if ($user->user_type === 'employer')
                                                    @if ($user->document)
                                                        <a target="_blank" href="{{ $user->document }}" class="btn btn-success btn-sm">View Document</a>
                                                    @else
                                                        <p>Pending</p>
                                                    @endif
                                                @else
                                                    <p>Pending</p>
                                                @endif



{{--                                                <div class="btn-group justify-center" role="group">--}}
{{--                                                    <a href="{{ route('admin.background.submission', $user->id ) }}" class="btn btn-primary btn-sm" title="View details">--}}
{{--                                                        <span class="fa fa-eye" aria-hidden="true"></span>--}}
{{--                                                    </a>--}}

{{--                                                </div>--}}


                                                {{--                                </form>--}}

                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div><!-- table-wrapper -->

                        </div><!-- br-pagebody -->
                    </div>

                </div><!--col-sm-9-->
            </div><!--row-->
        </div><!-- container -->

    </div><!-- CONTENT -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notification.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Successful!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if (session('failure'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> {{ session('failure') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif