routes/admin.php
<?php

use App\Http\Controllers\admin\AdController;
use App\Http\Controllers\admin\BannerController;
use App\Http\Controllers\admin\CategoriesController;
use App\Http\Controllers\admin\DatabaseProductController;
use App\Http\Controllers\admin\EducationalDetails;
use App\Http\Controllers\admin\FormsController;
use App\Http\Controllers\admin\HighlighController;
use App\Http\Controllers\admin\JobsController;
use App\Http\Controllers\admin\LocationController;
use App\Http\Controllers\admin\PackagesController;
use App\Http\Controllers\admin\PagesController;
use App\Http\Controllers\admin\ProductsController;
use App\Http\Controllers\admin\SettingsController;
use App\Http\Controllers\admin\TestimonialController;
use App\Http\Controllers\admin\UserBackgroundVerificationController;
use App\Http\Controllers\admin\UsersController;
use App\Http\Controllers\admin\VerificationPackageController;
use App\Http\Controllers\AdminDashboard;
use App\Http\Controllers\admin\AdminsController;
use App\Http\Controllers\admin\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\FunctionalAreaController;
use App\Http\Controllers\IndustryTypeController;
use App\Http\Controllers\LgaController;
use App\Http\Controllers\SkillsController;
use App\Http\Controllers\StateController;
use App\Models\DatabaseProduct;
use App\Models\UserBackgroundVerification;


Route::group(['middleware' => ['auth','role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('dashboard', AdminDashboard::class)->name('dashboard');

//    User Listing

    Route::get('user/admins', [UsersController::class, 'admins'])->name('user.admins');
    Route::get('user/sub_admins', [UsersController::class, 'subAdmins'])->name('user.sub_admins');
    Route::get('user/employers', [UsersController::class, 'employers'])->name('user.employers');
    Route::get('user/jobseekers', [UsersController::class, 'jobseekers'])->name('user.jobseekers');
    Route::post('settings/store/item', [SettingsController::class, 'storeItem'])->name('settings.store.item');

    Route::get('pages/edit/page', [PagesController::class, 'editPage'])->name('pages.edit.page');

    Route::get('resume/access', [AdminsController::class, 'resumeAccess'])->name('resume.access');
    Route::get('inactive/resumes', [AdminsController::class, 'inactiveResumes'])->name('inactive.resumes');
    Route::post('resume/search', [AdminsController::class, 'resumeSearch'])->name('resume.search');
    Route::get('inactive/companies', [AdminsController::class, 'inactiveCompanies'])->name('inactive.companies');

    Route::get('employee/database/access', [AdminsController::class, 'employeeDBAccess'])->name('employee.db.access');
    Route::get('employee/database/order', [AdminsController::class, 'employeeDBAccessOrders'])->name('employee.db.access.orders');
    Route::get('employee/job/access/order', [AdminsController::class, 'employeeJobAccessOrders'])->name('employee.job.access.orders');
    Route::get('employee/job/access', [AdminsController::class, 'employeeJobAccess'])->name('employee.job.access');

    Route::get('package/purchased', [AdminsController::class, 'packagePurchased'])->name('package.purchased');

    Route::get('background/forms', [FormsController::class, 'backgroundIndex'])->name('background.form.index');

    Route::get('background/submissions', [UserBackgroundVerificationController::class, 'index'])->name('background.submissions');

    Route::get('background/submission/{id}', [UserBackgroundVerificationController::class, 'show'])->name('background.submission');
    Route::get('background/upload/{id}', [UserBackgroundVerificationController::class, 'upload'])->name('background.upload');
    Route::post('background/upload/store', [UserBackgroundVerificationController::class, 'storeUpload'])->name('background.upload.store');
    Route::get('background/approve/{id}', [UserBackgroundVerificationController::class, 'approve'])->name('background.approve');

    Route::get('settings/home', [SettingsController::class, 'home'])->name('settings.home');

    Route::get('jobseeker/newsletter', [AdminsController::class, 'jobseekerNewsletter'])->name('jobseeker.newsletter');
    Route::get('employer/newsletter', [AdminsController::class, 'employerNewsletter'])->name('employer.newsletter');
    Route::post('newsletter/submit', [AdminsController::class, 'newsletterSubmit'])->name('newsletter.submit');

    Route::post('newsletter/send', [AdminsController::class, 'newsletterSend'])->name('newsletter.send');

    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    

    Route::resources([
        'countries' => CountryController::class,
        'highlights' => HighlighController::class,
        'users' => UsersController::class,
        'lgas' => LgaController::class,
        'states' => StateController::class,
        'cities' => CityController::class,
        'skills' => SkillsController::class,
        'industry-type'     => IndustryTypeController::class,
        'functional-area'   => FunctionalAreaController::class,
        'educational-details' => EducationalDetails::class,
        'products' => ProductsController::class,
        'ads' => AdController::class,
        'packages' => PackagesController::class,
        'pages' => PagesController::class,
        'banners' => BannerController::class,
        'settings' => SettingsController::class,
        'categories' => CategoriesController::class,
        'locations' => LocationController::class,
        'testimonial' => TestimonialController::class,
        'dbproducts' => DatabaseProductController::class,
        'v_packages' => VerificationPackageController::class,
        'forms' => FormsController::class,
        '/home/jobs' => JobsController::class,

    ]);

});

routes/web.php
<?php


use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobAlertController;
use App\Http\Controllers\JobsController;
use App\Http\Controllers\JobseekerController;
use App\Http\Controllers\admin\TempController;
use App\Http\Controllers\LocationsController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SocialAuthController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;



Route::get('login/{provider}', [SocialAuthController::class,'redirect'])->name('social.login');
Route::get('login/{provider}/callback', [SocialAuthController::class,'callback']);

Route::get('/',[HomeController::class, 'index'])->name('home');

Route::get('/similar/jobs',[JobsController::class, 'similar'])->name('similar');

Route::post('/contact/storeemp_resume_pack',[HomeController::class, 'storeContact'])->name('contact.store');


Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/testimonial',[HomeController::class, 'testimonial'])->name('testimonial');

Route::post('/testimonial/store',[HomeController::class, 'testimonialStore'])->name('testimonial.store');

Route::get('payment-razorpay',  [PaymentController::class,'create'])->name('paywithrazorpay');
Route::post('payment', [PaymentController::class,'payment'])->name('payment');
Route::post('verification/payment', [PaymentController::class,'verificationPayment'])->name('verification.payment');

Route::get('/about-us',[HomeController::class, 'about'])->name('about');
Route::get('/terms',[HomeController::class, 'terms'])->name('terms');
Route::get('/privacy',[HomeController::class, 'privacy'])->name('privacy');
Route::get('/faq',[HomeController::class, 'faq'])->name('faq');

Route::get('/getstates', [LocationsController::class, 'getstates'])->name('ajax.getstates');


Route::post('/payment/store', 'PaymentController@store')->name('payment.store');



Route::get('jobseeker-self-service', [HomeController::class, 'jobseekerSelfservice'])->name('selfservice');
Route::get('background-verification-request', [HomeController::class, 'backgroundVerificationRequest'])->name('bg_verification');
Route::get('background-verification-response', [HomeController::class, 'backgroundVerificationResponse'])->name('bg_verification_response');
Route::get('background-verification-payment/{id}', [HomeController::class, 'backgroundVerificationPayment'])->name('bg_verification_pay');
Route::get('background-verification', [HomeController::class,'backgroundVerification'])->name('background-verification');
Route::get('background-verification/2/{id}', [HomeController::class,'backgroundVerification2'])->name('background-verification-2');
Route::get('background-verification/3/{id}', [HomeController::class,'backgroundVerification3'])->name('background-verification-3');

Route::post('background-edu-store', [HomeController::class,'storeEdu'])->name('store.edu');
Route::post('background-employment-store', [HomeController::class,'storeEmployment'])->name('store.employment');
Route::post('background-ref-store', [HomeController::class,'storeRef'])->name('store.ref');

//Route::view('background-verification/2', 'background-verification2')->name('background-verification-2');
//Route::view('background-verification/3', 'background-verification3')->name('background-verification-3');


Route::post('/advance_search',[JobsController::class, 'advanceSearch'])->name('advance_search');

Route::get('/company/{id}/jobs',[JobsController::class, 'companyAllJobs'])->name('company.all.jobs');

Route::resources([
    'users' => UsersController::class,
]);

Route::post('/update/password',[UsersController::class, 'updatePassword'])->name('update.password');

Route::post('/mail/job',[HomeController::class, 'mailJob'])->name('mail.job');
Route::post('/mail/employer',[HomeController::class, 'mailEmployer'])->name('mail.employer');


Route::get('/jobseeker-registeration', [UsersController::class,'jobseekerReg'])->name('jobseeker.reg');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/jobseeker/register', [UsersController::class, 'jobseekerReg'])->name('jobseeker.register');
    Route::get('/jobseeker/login', [UsersController::class, 'jobseekerLogin'])->name('jobseeker.login');

    Route::get('/employer/register', [UsersController::class,'employerReg'])->name('employer.register');
    Route::get('/employer/login', [UsersController::class,'employerLogin'])->name('employer.login');

});

Route::Resources(['job_alerts' => JobAlertController::class]);


Route::group(['prefix' => 'jobseeker','middleware' => ['verified','auth','role:jobseeker|admin']], function () {

    Route::get('/profile', [JobseekerController::class, 'profile'])->name('jobseeker.profile');
    Route::get('/manage/employers', [JobseekerController::class, 'employers'])->name('jobseeker.manage.employers');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/edit-employee/{id}', [JobseekerController::class,'editEmployee'])->name('edit_emp');
    Route::post('/delete-employee/{id}', [JobseekerController::class,'deleteEmployer'])->name('delete_emp');

    Route::post('/job/apply', [JobsController::class,'apply'])->name('job.apply');



});


Route::group(['middleware' => ['verified','auth']], function () {

    Route::post('/user/update/resume', [UsersController::class, 'updateResume'])->name('user.update.resume');
    Route::post('/user/create/employer', [UsersController::class, 'storeEmployer'])->name('user.create.employer');

    Route::post('/user/update/account', [UsersController::class, 'update'])->name('user.account.update');
    Route::post('/user/update/summary', [UsersController::class, 'updateSummary'])->name('user.account.summary');
    Route::post('/user/update/more', [UsersController::class, 'updateMore'])->name('user.update.more');
    Route::post('/user/update/education', [UsersController::class, 'updateEducation'])->name('user.update.education');

    Route::get('/user/profile/{username}', [UsersController::class, 'userProfile'])->name('user.profile.public');
    Route::get('/user/download/resume/{username}', [UsersController::class, 'downloadResume'])->name('user.resume.download');

    Route::post('/user/update/itskills', [UsersController::class, 'updateItskills'])->name('user.update.itskills');

    Route::post('/user/update/avatar', [UsersController::class, 'updateAvatar'])->name('user.update.avatar');
    Route::post('/user/update/visibility', [UsersController::class, 'updateVisibility'])->name('user.update.visibility');

    Route::get('/edit-summary-info', [UsersController::class,'editSummary'])->name('edit_summary');
    Route::get('/create-employee', [JobseekerController::class,'createEmployee'])->name('create_emp');
    Route::get('/edit-resume-detail', [JobseekerController::class,'editResume'])->name('edit_resume_det');
    Route::get('/itskills', [JobseekerController::class,'itSkills'])->name('itskills');
    Route::get('/educationdetails', [JobseekerController::class,'eduDetails'])->name('educational_details');
    Route::get('/moredetails', [JobseekerController::class,'moredetails'])->name('moredetails');
    Route::get('/jobseeker-profile-edit', [JobseekerController::class,'profileEdit'])->name('jobseeker-edit');

});

Route::group(['prefix' => 'employer','middleware' => ['verified','auth','role:employer|admin']], function () {


    Route::post('/purchase/plan',[HomeController::class, 'purchasePlan'])->name('plan.purchase');


    Route::get('/profile', [EmployerController::class, 'profile'])->name('employer.profile');
    Route::get('/emp_resume_pack', [EmployerController::class, 'empResumePack'])->name('employer.resume_pack');
    Route::get('/transactions', [EmployerController::class, 'Transactions'])->name('employer.transactions');
    Route::get('/transaction/payment/{type}/{id}', [EmployerController::class, 'TransactionPayment'])->name('employer.transaction.payment');
    Route::get('/sub_users', [EmployerController::class, 'subUsers'])->name('employer.sub_users');
    Route::get('/add_sub_user', [EmployerController::class, 'addSubUser'])->name('employer.add_sub_user');

    Route::get('/featured_resume', [EmployerController::class, 'featuredResume'])->name('employer.featured_resumes');
    Route::post('/search_resume', [EmployerController::class, 'searchResume'])->name('search_resumes');

    Route::get('/change/password', [EmployerController::class, 'changePassword'])->name('employer.change_password');
    Route::get('/job/{slug}', [JobsController::class, 'view'])->name('jobs.job.view');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/job/{id}/responses', [JobsController::class, 'response'])->name('job.response');


    Route::get('/jobs/deleted', [JobsController::class, 'deleted'])->name('jobs.deleted');
    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    Route::get('/jobs/restore/deleted/job/{slug}/{id}', [JobsController::class, 'restore'])->name('jobs.restore');
    Route::post('/jobs/force/delete/{id}', [JobsController::class, 'forceDelete'])->name('jobs.delete');

    Route::post('/user/update', [UsersController::class, 'updateProfile'])->name('user.update');
    Route::post('/user/store/sub', [UsersController::class, 'storeSubUser'])->name('user.sub.store');

    Route::resources([
        'jobs' => JobsController::class,
        'companies' => CompaniesController::class,
        'jobs' => jobsController::class,
        ]);
});




Route::get('/all-jobs', [JobsController::class, 'allJobs'])->name('all_jobs');

Route::get('/job/{slug}', [JobsController::class, 'jobView'])->name('jobs.job.view');


Route::get('/jobs-by-area', [JobsController::class,'jobByArea'])->name('job_by_area');

resources/views/admin/notification.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Successful!</strong> {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

@if (session('failure'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> {{ session('failure') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/admin/resume_access.blade.php
@extends('admin.layouts.admin-app')


@section('content')
<!-- ########## START: MAIN PANEL ########## -->
<div class="br-mainpanel">
    <div class="br-pageheader pd-y-15 pd-l-20">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{ route('admin.dashboard') }}">Dashbord</a>
            <a class="breadcrumb-item" href="{{ route('admin.industry-type.index') }}">Industry Type</a>
            <span class="breadcrumb-item active">Industry Type Edit</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <h4 class="tx-gray-800 mg-b-5"> Industry Type Edit</h4>
    </div>



    <div class="br-pagebody">
            <div class="br-section-wrapper">
                @include('notification')
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('admin.resume.search') }}" method="POST">
                    @csrf

                    <div class="form-layout form-layout-1">

                        <div class="row mg-b-25">
                            <div class="col-md-6">
                                <label class="form-control-label">Functional Area: <span class="tx-danger">*</span></label>

                                <select class="form-control select2" data-placeholder="Choose Functional Area" name="functional_area">
                                                                            <option>Choose functional Area</option>
                                    @foreach (\App\Models\FunctionalArea::pluck('category_functional_area') as $item)
                                        <option value="{{ $item }}">{{ $item }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label class="form-control-label">Industry Type: <span class="tx-danger">*</span></label>

                                <select class="form-control select2" data-placeholder="Choose Industry Type" name="industry_type">
                                                                            <option>Choose Industry Type</option>
                                    @foreach (\App\Models\IndustryType::pluck('category') as $item)
                                        <option value="{{ $item }}">{{ $item }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Keyword : </label>
                                    <input class="form-control" type="text" name="keyword" />
                                </div>
                            </div><!-- col-4 -->
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Experience From: </label>
                                    <select class="form-control select2" data-placeholder="Choose Exp From" name="exp_from">
                                        <option value="">Year</option>
                                        <option value="0">0</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                        <option value="16">16</option>
                                        <option value="17">17</option>
                                        <option value="18">18</option>
                                        <option value="19">19</option>
                                        <option value="20">20</option>
                                        <option value="21">21</option>
                                        <option value="22">22</option>
                                        <option value="23">23</option>
                                        <option value="24">24</option>
                                        <option value="25">25</option>
                                        <option value="26">26</option>
                                        <option value="27">27</option>
                                        <option value="28">28</option>
                                        <option value="29">29</option>
                                    </select>
                                </div>
                            </div><!-- col-4 -->
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Experience To: </label>
                                    <select class="form-control select2" data-placeholder="Choose Exp From" name="exp_to">
                                        <option value="">Year</option>
                                        <option value="0">0</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                        <option value="16">16</option>
                                        <option value="17">17</option>
                                        <option value="18">18</option>
                                        <option value="19">19</option>
                                        <option value="20">20</option>
                                        <option value="21">21</option>
                                        <option value="22">22</option>
                                        <option value="23">23</option>
                                        <option value="24">24</option>
                                        <option value="25">25</option>
                                        <option value="26">26</option>
                                        <option value="27">27</option>
                                        <option value="28">28</option>
                                        <option value="29">29</option>
                                    </select>
                                </div>
                            </div><!-- col-4 -->

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Location : </label>
                                    <input class="form-control" type="text" name="location" />
                                </div>
                            </div><!-- col-4 -->

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Country: </label>
                                    <select class="form-control select2" data-placeholder="Choose Country" name="country">
                                        <option value="">Country</option>
                                    @foreach(\App\Models\Country::pluck('name') as $item)
                                       <option value="{{ $item }}">{{ $item }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div><!-- col-4 -->
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="form-control-label">Qualification: </label>
                                    <select class="form-control select2" data-placeholder="Choose Qualification" name="qualification">
                                        <option value="">Qualification</option>
                                    @foreach(\App\Models\EducationDetails::pluck('name') as $item)
                                       <option value="{{ $item }}">{{ $item }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div><!-- col-4 -->




                        </div><!-- row -->

                        <div class="form-layout-footer">
                            <button class="btn btn-info" type="submit">Search </button>
                        </div><!-- form-layout-footer -->
                    </div><!-- form-layout -->
                </form>
            </div><!-- br-section-wrapper -->
    </div>



@endsection

resources/views/admin/skills-edit.blade.php
@extends('admin.layouts.admin-app')

@section('style')
    <link href="{{ asset('lib/highlightjs/github.css')}}" rel="stylesheet">
    <link href="{{ asset('lib/datatables/jquery.dataTables.css')}}" rel="stylesheet">
    <link href="{{ asset('lib/select2/css/select2.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<!-- ########## START: MAIN PANEL ########## -->
<div class="br-mainpanel">
    <div class="br-pageheader pd-y-15 pd-l-20">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{ route('admin.dashboard') }}">Bracket</a>
            <a class="breadcrumb-item" href="#">Skills</a>
            <span class="breadcrumb-item active">Skills Layouts</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <h4 class="tx-gray-800 mg-b-5"> Key Skills</h4>
    </div>

    <div class="br-pagebody">
        <div class="br-section-wrapper">
            <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10">Edit Skill</h6>

            <form action="{{ route('admin.skills.update',$skills->id) }}" method="POST">
                @csrf
{{--                @method('PUT')--}}
                <input name="_method" type="hidden" value="PUT">
                <div class="form-layout form-layout-1">
                    <div class="d-flex align-items-center justify-content-center bg-gray-100 ht-md-80 bd pd-x-20">
                        <div class="d-md-flex pd-y-20 pd-md-y-0">
                            <input type="text" name="skill_name" value="{{ old('skill_name', optional($skills)->skill_name ) }}" class="form-control mg-md-l-10 mg-t-10 mg-md-t-0 col-lg-12" placeholder="Enter Skill">
                            <button class="btn btn-info pd-y-13 pd-x-20 bd-0 mg-md-l-10 mg-t-10 mg-md-t-0 tx-uppercase tx-11 tx-spacing-2"> Update</button>
                        </div>
                    </div><!-- d-flex -->

                </div><!-- form-layout -->
            </form>
        </div><!-- br-section-wrapper -->



<!-- ########## END: MAIN PANEL ########## -->

        @section('js')
            <script src="{{ asset('lib/jquery-ui/jquery-ui.js') }}"></script>
            <script src="{{ asset('lib/jquery-switchbutton/jquery.switchButton.js') }}"></script>
            <script src="{{ asset('lib/peity/jquery.peity.js') }}"></script>
            <script src="{{ asset('lib/datatables/jquery.dataTables.js') }}"></script>
            <script src="{{ asset('lib/datatables-responsive/dataTables.responsive.js') }}"></script>
            <script src="{{ asset('lib/select2/js/select2.min.js') }}"></script>
            <script src="{{ asset('lib/highlightjs/highlight.pack.js') }}"></script>
            <script>
                $(function(){
                    'use strict';

                    $('#datatable1').DataTable({
                        responsive: true,
                        language: {
                            searchPlaceholder: 'Search...',
                            sSearch: '',
                            lengthMenu: '_MENU_ items/page',
                        }
                    });

                    $('#datatable2').DataTable({
                        bLengthChange: false,
                        searching: false,
                        responsive: true
                    });

                    // Select2
                    $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

                });
            </script>
       @endsection

@endsection