routes/admin.php
<?php

use App\Http\Controllers\admin\AdController;
use App\Http\Controllers\admin\BannerController;
use App\Http\Controllers\admin\CategoriesController;
use App\Http\Controllers\admin\DatabaseProductController;
use App\Http\Controllers\admin\EducationalDetails;
use App\Http\Controllers\admin\FormsController;
use App\Http\Controllers\admin\HighlighController;
use App\Http\Controllers\admin\JobsController;
use App\Http\Controllers\admin\LocationController;
use App\Http\Controllers\admin\PackagesController;
use App\Http\Controllers\admin\PagesController;
use App\Http\Controllers\admin\ProductsController;
use App\Http\Controllers\admin\SettingsController;
use App\Http\Controllers\admin\TestimonialController;
use App\Http\Controllers\admin\UserBackgroundVerificationController;
use App\Http\Controllers\admin\UsersController;
use App\Http\Controllers\admin\VerificationPackageController;
use App\Http\Controllers\AdminDashboard;
use App\Http\Controllers\admin\AdminsController;
use App\Http\Controllers\admin\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\FunctionalAreaController;
use App\Http\Controllers\IndustryTypeController;
use App\Http\Controllers\LgaController;
use App\Http\Controllers\SkillsController;
use App\Http\Controllers\StateController;
use App\Models\DatabaseProduct;
use App\Models\UserBackgroundVerification;


Route::group(['middleware' => ['auth','role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('dashboard', AdminDashboard::class)->name('dashboard');

//    User Listing

    Route::get('user/admins', [UsersController::class, 'admins'])->name('user.admins');
    Route::get('user/sub_admins', [UsersController::class, 'subAdmins'])->name('user.sub_admins');
    Route::get('user/employers', [UsersController::class, 'employers'])->name('user.employers');
    Route::get('user/jobseekers', [UsersController::class, 'jobseekers'])->name('user.jobseekers');
    Route::post('settings/store/item', [SettingsController::class, 'storeItem'])->name('settings.store.item');

    Route::get('pages/edit/page', [PagesController::class, 'editPage'])->name('pages.edit.page');

    Route::get('resume/access', [AdminsController::class, 'resumeAccess'])->name('resume.access');
    Route::get('inactive/resumes', [AdminsController::class, 'inactiveResumes'])->name('inactive.resumes');
    Route::post('resume/search', [AdminsController::class, 'resumeSearch'])->name('resume.search');
    Route::get('inactive/companies', [AdminsController::class, 'inactiveCompanies'])->name('inactive.companies');

    Route::get('employee/database/access', [AdminsController::class, 'employeeDBAccess'])->name('employee.db.access');
    Route::get('employee/database/order', [AdminsController::class, 'employeeDBAccessOrders'])->name('employee.db.access.orders');
    Route::get('employee/job/access/order', [AdminsController::class, 'employeeJobAccessOrders'])->name('employee.job.access.orders');
    Route::get('employee/job/access', [AdminsController::class, 'employeeJobAccess'])->name('employee.job.access');

    Route::get('package/purchased', [AdminsController::class, 'packagePurchased'])->name('package.purchased');

    Route::get('background/forms', [FormsController::class, 'backgroundIndex'])->name('background.form.index');

    Route::get('background/submissions', [UserBackgroundVerificationController::class, 'index'])->name('background.submissions');

    Route::get('background/submission/{id}', [UserBackgroundVerificationController::class, 'show'])->name('background.submission');
    Route::get('background/upload/{id}', [UserBackgroundVerificationController::class, 'upload'])->name('background.upload');
    Route::post('background/upload/store', [UserBackgroundVerificationController::class, 'storeUpload'])->name('background.upload.store');
    Route::get('background/approve/{id}', [UserBackgroundVerificationController::class, 'approve'])->name('background.approve');

    Route::get('settings/home', [SettingsController::class, 'home'])->name('settings.home');

    Route::get('jobseeker/newsletter', [AdminsController::class, 'jobseekerNewsletter'])->name('jobseeker.newsletter');
    Route::get('employer/newsletter', [AdminsController::class, 'employerNewsletter'])->name('employer.newsletter');
    Route::post('newsletter/submit', [AdminsController::class, 'newsletterSubmit'])->name('newsletter.submit');

    Route::post('newsletter/send', [AdminsController::class, 'newsletterSend'])->name('newsletter.send');

    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    

    Route::resources([
        'countries' => CountryController::class,
        'highlights' => HighlighController::class,
        'users' => UsersController::class,
        'lgas' => LgaController::class,
        'states' => StateController::class,
        'cities' => CityController::class,
        'skills' => SkillsController::class,
        'industry-type'     => IndustryTypeController::class,
        'functional-area'   => FunctionalAreaController::class,
        'educational-details' => EducationalDetails::class,
        'products' => ProductsController::class,
        'ads' => AdController::class,
        'packages' => PackagesController::class,
        'pages' => PagesController::class,
        'banners' => BannerController::class,
        'settings' => SettingsController::class,
        'categories' => CategoriesController::class,
        'locations' => LocationController::class,
        'testimonial' => TestimonialController::class,
        'dbproducts' => DatabaseProductController::class,
        'v_packages' => VerificationPackageController::class,
        'forms' => FormsController::class,
        '/home/jobs' => JobsController::class,

    ]);

});

routes/web.php
<?php


use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobAlertController;
use App\Http\Controllers\JobsController;
use App\Http\Controllers\JobseekerController;
use App\Http\Controllers\admin\TempController;
use App\Http\Controllers\LocationsController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SocialAuthController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;



Route::get('login/{provider}', [SocialAuthController::class,'redirect'])->name('social.login');
Route::get('login/{provider}/callback', [SocialAuthController::class,'callback']);

Route::get('/',[HomeController::class, 'index'])->name('home');

Route::get('/similar/jobs',[JobsController::class, 'similar'])->name('similar');

Route::post('/contact/storeemp_resume_pack',[HomeController::class, 'storeContact'])->name('contact.store');


Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/home',[HomeController::class, 'index'])->name('auth.home');
Route::get('/testimonial',[HomeController::class, 'testimonial'])->name('testimonial');

Route::post('/testimonial/store',[HomeController::class, 'testimonialStore'])->name('testimonial.store');

Route::get('payment-razorpay',  [PaymentController::class,'create'])->name('paywithrazorpay');
Route::post('payment', [PaymentController::class,'payment'])->name('payment');
Route::post('verification/payment', [PaymentController::class,'verificationPayment'])->name('verification.payment');

Route::get('/about-us',[HomeController::class, 'about'])->name('about');
Route::get('/terms',[HomeController::class, 'terms'])->name('terms');
Route::get('/privacy',[HomeController::class, 'privacy'])->name('privacy');
Route::get('/faq',[HomeController::class, 'faq'])->name('faq');

Route::get('/getstates', [LocationsController::class, 'getstates'])->name('ajax.getstates');


Route::post('/payment/store', 'PaymentController@store')->name('payment.store');



Route::get('jobseeker-self-service', [HomeController::class, 'jobseekerSelfservice'])->name('selfservice');
Route::get('background-verification-request', [HomeController::class, 'backgroundVerificationRequest'])->name('bg_verification');
Route::get('background-verification-response', [HomeController::class, 'backgroundVerificationResponse'])->name('bg_verification_response');
Route::get('background-verification-payment/{id}', [HomeController::class, 'backgroundVerificationPayment'])->name('bg_verification_pay');
Route::get('background-verification', [HomeController::class,'backgroundVerification'])->name('background-verification');
Route::get('background-verification/2/{id}', [HomeController::class,'backgroundVerification2'])->name('background-verification-2');
Route::get('background-verification/3/{id}', [HomeController::class,'backgroundVerification3'])->name('background-verification-3');

Route::post('background-edu-store', [HomeController::class,'storeEdu'])->name('store.edu');
Route::post('background-employment-store', [HomeController::class,'storeEmployment'])->name('store.employment');
Route::post('background-ref-store', [HomeController::class,'storeRef'])->name('store.ref');

//Route::view('background-verification/2', 'background-verification2')->name('background-verification-2');
//Route::view('background-verification/3', 'background-verification3')->name('background-verification-3');


Route::post('/advance_search',[JobsController::class, 'advanceSearch'])->name('advance_search');

Route::get('/company/{id}/jobs',[JobsController::class, 'companyAllJobs'])->name('company.all.jobs');

Route::resources([
    'users' => UsersController::class,
]);

Route::post('/update/password',[UsersController::class, 'updatePassword'])->name('update.password');

Route::post('/mail/job',[HomeController::class, 'mailJob'])->name('mail.job');
Route::post('/mail/employer',[HomeController::class, 'mailEmployer'])->name('mail.employer');


Route::get('/jobseeker-registeration', [UsersController::class,'jobseekerReg'])->name('jobseeker.reg');

Route::group(['middleware' => ['guest']], function () {
    Route::get('/jobseeker/register', [UsersController::class, 'jobseekerReg'])->name('jobseeker.register');
    Route::get('/jobseeker/login', [UsersController::class, 'jobseekerLogin'])->name('jobseeker.login');

    Route::get('/employer/register', [UsersController::class,'employerReg'])->name('employer.register');
    Route::get('/employer/login', [UsersController::class,'employerLogin'])->name('employer.login');

});

Route::Resources(['job_alerts' => JobAlertController::class]);


Route::group(['prefix' => 'jobseeker','middleware' => ['verified','auth','role:jobseeker|admin']], function () {

    Route::get('/profile', [JobseekerController::class, 'profile'])->name('jobseeker.profile');
    Route::get('/manage/employers', [JobseekerController::class, 'employers'])->name('jobseeker.manage.employers');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/edit-employee/{id}', [JobseekerController::class,'editEmployee'])->name('edit_emp');
    Route::post('/delete-employee/{id}', [JobseekerController::class,'deleteEmployer'])->name('delete_emp');

    Route::post('/job/apply', [JobsController::class,'apply'])->name('job.apply');



});


Route::group(['middleware' => ['verified','auth']], function () {

    Route::post('/user/update/resume', [UsersController::class, 'updateResume'])->name('user.update.resume');
    Route::post('/user/create/employer', [UsersController::class, 'storeEmployer'])->name('user.create.employer');

    Route::post('/user/update/account', [UsersController::class, 'update'])->name('user.account.update');
    Route::post('/user/update/summary', [UsersController::class, 'updateSummary'])->name('user.account.summary');
    Route::post('/user/update/more', [UsersController::class, 'updateMore'])->name('user.update.more');
    Route::post('/user/update/education', [UsersController::class, 'updateEducation'])->name('user.update.education');

    Route::get('/user/profile/{username}', [UsersController::class, 'userProfile'])->name('user.profile.public');
    Route::get('/user/download/resume/{username}', [UsersController::class, 'downloadResume'])->name('user.resume.download');

    Route::post('/user/update/itskills', [UsersController::class, 'updateItskills'])->name('user.update.itskills');

    Route::post('/user/update/avatar', [UsersController::class, 'updateAvatar'])->name('user.update.avatar');
    Route::post('/user/update/visibility', [UsersController::class, 'updateVisibility'])->name('user.update.visibility');

    Route::get('/edit-summary-info', [UsersController::class,'editSummary'])->name('edit_summary');
    Route::get('/create-employee', [JobseekerController::class,'createEmployee'])->name('create_emp');
    Route::get('/edit-resume-detail', [JobseekerController::class,'editResume'])->name('edit_resume_det');
    Route::get('/itskills', [JobseekerController::class,'itSkills'])->name('itskills');
    Route::get('/educationdetails', [JobseekerController::class,'eduDetails'])->name('educational_details');
    Route::get('/moredetails', [JobseekerController::class,'moredetails'])->name('moredetails');
    Route::get('/jobseeker-profile-edit', [JobseekerController::class,'profileEdit'])->name('jobseeker-edit');

});

Route::group(['prefix' => 'employer','middleware' => ['verified','auth','role:employer|admin']], function () {


    Route::post('/purchase/plan',[HomeController::class, 'purchasePlan'])->name('plan.purchase');


    Route::get('/profile', [EmployerController::class, 'profile'])->name('employer.profile');
    Route::get('/emp_resume_pack', [EmployerController::class, 'empResumePack'])->name('employer.resume_pack');
    Route::get('/transactions', [EmployerController::class, 'Transactions'])->name('employer.transactions');
    Route::get('/transaction/payment/{type}/{id}', [EmployerController::class, 'TransactionPayment'])->name('employer.transaction.payment');
    Route::get('/sub_users', [EmployerController::class, 'subUsers'])->name('employer.sub_users');
    Route::get('/add_sub_user', [EmployerController::class, 'addSubUser'])->name('employer.add_sub_user');

    Route::get('/featured_resume', [EmployerController::class, 'featuredResume'])->name('employer.featured_resumes');
    Route::post('/search_resume', [EmployerController::class, 'searchResume'])->name('search_resumes');

    Route::get('/change/password', [EmployerController::class, 'changePassword'])->name('employer.change_password');
    Route::get('/job/{slug}', [JobsController::class, 'view'])->name('jobs.job.view');
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::get('/job/{id}/responses', [JobsController::class, 'response'])->name('job.response');


    Route::get('/jobs/deleted', [JobsController::class, 'deleted'])->name('jobs.deleted');
    Route::get('/jobs/toggle/disabled/{slug}', [JobsController::class, 'toggleDisabled'])->name('jobs.toggle_disabled');
    Route::get('/jobs/restore/deleted/job/{slug}/{id}', [JobsController::class, 'restore'])->name('jobs.restore');
    Route::post('/jobs/force/delete/{id}', [JobsController::class, 'forceDelete'])->name('jobs.delete');

    Route::post('/user/update', [UsersController::class, 'updateProfile'])->name('user.update');
    Route::post('/user/store/sub', [UsersController::class, 'storeSubUser'])->name('user.sub.store');

    Route::resources([
        'jobs' => JobsController::class,
        'companies' => CompaniesController::class,
        'jobs' => jobsController::class,
        ]);
});




Route::get('/all-jobs', [JobsController::class, 'allJobs'])->name('all_jobs');

Route::get('/job/{slug}', [JobsController::class, 'jobView'])->name('jobs.job.view');


Route::get('/jobs-by-area', [JobsController::class,'jobByArea'])->name('job_by_area');

resources/views/admin/jobs/edit.blade.php
@extends('admin.layouts.admin-app')

@section('content')
    <!-- ########## START: MAIN PANEL ########## -->
    <div class="br-mainpanel">

        <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30" style="position:center; ">
            <h4 class="tx-gray-800 mg-b-5">Editing {{ $job->title }}</h4>
        </div>

        <div class="br-pagebody">
            <div class="br-section-wrapper">

                <div class="row mg-t-10">
                    <div class="col-xl-12">

                        @if ($errors->any())

                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif


                        @if(session()->has('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success_message') }}
                            </div>
                        @endif


                            <form class="form-horizontal m10" action="{{ route('admin.jobs.update', $job->id) }}" method="post" enctype="multipart/form-data">

                                @csrf

                    

                                <input name="_method" type="hidden" value="PUT">

                                <input name="user_id" type="hidden" value="{{ $job->user_id }}">

                                <input name="company_id" type="hidden" value="{{ $job->company_id }}">

                                

                                <div class="row">

                                    <div class="card card-body">


                                    @include('admin.jobs.form')

                                <div class="row mt-4">
                                    <div class="col-sm-12">
                                        <div class="col-sm-6">
                                            <div class="col-sm-3"><input type="submit" class="btn-blue pdng-btn1 btn" value="Update Job"></div>
                                            {{-- <div class="col-sm-3"><div class="btn-blue pdng-btn1 btn"><a href="{{ route('jobs.create') }}" style="color:#FFF"> Cancel </a></div></div> --}}
                                        </div> <!--col-md-6-->
                                    </div>
                                </div>
                                </div>
                                </div>

                            </form>

                    </div><!-- col-6 -->

                </div>
            </div>

        </div><!-- br-mainpanel -->
@endsection

resources/views/admin/jobs/list.blade.php
@extends('admin.layouts.admin-app')

@section('style')
    @include('admin.partials.dt-css')
@endsection

@section('js')
    @include('admin.partials.dt-js')
@endsection

@section('content')
    <!-- ########## START: MAIN PANEL ########## -->
    <div class="br-mainpanel">
        <div class="br-pageheader pd-y-15 pd-l-20">
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="{{ route('admin.dashboard') }}">Dashboard</a>

            </nav>
        </div><!-- br-pageheader -->
        <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
            <h4 class="tx-gray-800 mg-b-5">Jobs List</h4>
        </div>

        <div class="br-pagebody">
            <div class="br-section-wrapper">
                @include('notification')
                <h6 class="tx-gray-800 tx-uppercase tx-bold tx-14 mg-b-10" style="padding-bottom: 50px">Jobs List
{{--                    <a href="{{ route('admin.jobs.create') }}"><button class="btn btn-success" style="float: right"> Add New</button></a>--}}
                </h6>
                <div class="table-wrapper table-responsive">
                    <table id="datatable1" class="table table-condensed table-bordered display responsive nowra">
                        <thead>
                        <tr>
                            <th class="">S/N</th>
                            <th class="wd-20p">Title</th>
                            <th class="wd-10p">Industry</th>
                            <th class="wd-15p">Company</th>
                            <th class="wd-15p">Date Posted</th>
                            {{-- <th class="wd-20p">Keywords</th> --}}
                            <th class="wd-10p">Response</th>
                            <th class="wd-20p">Action</th>
                            {{--                            <th></th>--}}
                        </tr>
                        </thead>
                        <tbody>
                        <input type="hidden" value="{{ $i=1 }}">
                        @foreach ($jobs as $item)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $item->title }}
                                <br>
                                @if($item->is_active)
                                <span class="badge badge-success">Activated</span>
                                @else
                                <span class="badge badge-danger">Not Active</span>
                                @endif
                                </td>
                                <td>{{ optional($item->industry)->category }}</td>
                                <td>{{ optional($item->company)->name }}</td>
                                <td>{{ $item->created_at->format('d-M-Y')}}</td>
                                {{-- <td>{{ $item->keywords }}</td> --}}
                                <td>{{ count($item->applied_job) }}</td>


                                <td class="p-1">
                                    <form method="POST" action="{!! route('jobs.destroy', $item->id) !!}" accept-charset="UTF-8">
                                        <input name="_method" value="DELETE" type="hidden">
                                        {{ csrf_field() }}

                                        <div class="btn-group justify-center" role="group">
                                            <a href="{{ route('jobs.show', $item->slug ) }}" target="_blank" class="btn btn-info btn-sm" title="Public View">
                                                <span class="fa fa-eye" aria-hidden="true"></span>
                                            </a>
                                            @if ($item->is_active)
                                            
                                                <a href="{{ route('admin.jobs.toggle_disabled', $item->slug) }}" class="btn btn-warning btn-sm" title="deactivate job">
                                                    <span class="fa fa-remove" aria-hidden="true"></span>
                                                </a>
                                            @else
                                            <a href="{{ route('admin.jobs.toggle_disabled', $item->slug ) }}" class="btn btn-success btn-sm" title="activate job">
                                                <span class="fa fa-check" aria-hidden="true"></span>
                                            </a>
                                            @endif

                                            <a href="{{ route('admin.jobs.edit', $item->slug ) }}" class="btn btn-primary btn-sm" title="Edit Job">
                                                <span class="fa fa-edit" aria-hidden="true"></span>
                                            </a>

                                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Job" onclick="return confirm(&quot;Click Ok to delete Job.&quot;)">
                                                <span class="fa fa-trash" aria-hidden="true"></span>
                                            </button>
                                        </div>

                                    </form>
                                    {{--                                            <a href="emp_postedjobs.php?act_id=31602575081&act">--}}
                                    {{--                                                <img src="images/ico_active_1.png" width="20">--}}
                                    {{--                                            </a>--}}
                                    {{--                                            <a href="emp_postjob_edit.php?edit_id=31602575081" onClick="if(confirm('Do you want to edit this job')) { return true; } else { return false; }">--}}
                                    {{--                                                <img src="images/edit-1.gif" border="0" />--}}
                                    {{--                                            </a>--}}

                                    {{--                                            <a href="delete_posted_job.php?id=31602575081"><img src="images/delete-11.png" border="0" /></a>--}}

                                    {{--                                            <a href="javascript:void(0);" onclick = "alert('Job posted today only'); " title="Click to refresh"><img src="images/refresh.png" width="16" border="0"  /></a>--}}
                                    {{--                                       --}}

                                </td>

                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div><!-- table-wrapper -->





            </div>

@endsection